In [11]:
import pandas as pd
from scipy.stats import wilcoxon
from itertools import combinations
import numpy as np
from statsmodels.sandbox.stats.multicomp import multipletests

In [6]:
df = pd.read_csv('AUCs.txt', sep='\t')

In [10]:
clf_combinations = list(combinations(df.columns[1:], 2))
p_values = np.zeros(len(clf_combinations))
for i, clf_pair in enumerate(clf_combinations):
    p_values[i] = wilcoxon(df[clf_pair[0]], df[clf_pair[1]]).pvalue
print p_values
print np.count_nonzero(p_values < 0.05)

[ 0.01075713  0.86126233  0.01590644  0.04633273  0.32782568  0.0229091 ]
4


In [12]:
multipletests(p_values, alpha=0.05, method='holm')

(array([False, False, False, False, False, False], dtype=bool),
 array([ 0.0645428 ,  0.86126233,  0.07953222,  0.13899819,  0.65565135,
         0.0916364 ]),
 0.008512444610847103,
 0.008333333333333333)

In [13]:
multipletests(p_values, alpha=0.05, method='fdr_bh')

(array([ True, False,  True, False, False,  True], dtype=bool),
 array([ 0.0458182 ,  0.86126233,  0.0458182 ,  0.06949909,  0.39339081,
         0.0458182 ]),
 0.008512444610847103,
 0.008333333333333333)

In [14]:
import sys
print sys.version_info

sys.version_info(major=2, minor=7, micro=12, releaselevel='final', serial=0)
