In [12]:
import pandas as pd
from scipy.stats import wilcoxon
from itertools import combinations
import numpy as np
from statsmodels.sandbox.stats.multicomp import multipletests

In [13]:
df = pd.read_csv('AUCs.txt', sep='\t')

In [14]:
clf_combinations = list(combinations(df.columns[1:], 2))
p_values = np.zeros(len(clf_combinations))
for i, clf_pair in enumerate(clf_combinations):
    p_values[i] = wilcoxon(df[clf_pair[0]], df[clf_pair[1]]).pvalue
print p_values
print np.count_nonzero(p_values < 0.05)

[ 0.01075713  0.86126233  0.01587436  0.05432871  0.32782568  0.02531352]
3


In [15]:
multipletests(p_values, alpha=0.05, method='holm')

(array([False, False, False, False, False, False], dtype=bool),
 array([ 0.0645428 ,  0.86126233,  0.0793718 ,  0.16298614,  0.65565135,
         0.10125408]),
 0.008512444610847103,
 0.008333333333333333)

In [16]:
multipletests(p_values, alpha=0.05, method='fdr_bh')

(array([ True, False,  True, False, False, False], dtype=bool),
 array([ 0.04762308,  0.86126233,  0.04762308,  0.08149307,  0.39339081,
         0.05062704]),
 0.008512444610847103,
 0.008333333333333333)

In [17]:
import sys
print sys.version_info

sys.version_info(major=2, minor=7, micro=12, releaselevel='final', serial=0)
